name: Push and PR 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-uri: 964993353079.dkr.ecr.eu-west-3.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Build the backend Docker image 
        run: docker build -t trivia-backend ./backend

      - name: Tag the backend Docker image 
        run: docker tag trivia-backend:latest 964993353079.dkr.ecr.eu-west-3.amazonaws.com/trivia-backend:latest
      
      - name: Push the backend Docker image 
        run: docker push 964993353079.dkr.ecr.eu-west-3.amazonaws.com/trivia-backend:latest
        
      - name: Build the frontend Docker image 
        run: docker build -t trivia-frontend ./frontend
      
      - name: Tag the frontend Docker image 
        run: docker tag trivia-frontend:latest 964993353079.dkr.ecr.eu-west-3.amazonaws.com/trivia-frontend:latest
        
      - name: Push the frontend Docker image 
        run: docker push 964993353079.dkr.ecr.eu-west-3.amazonaws.com/trivia-frontend:latest
